version: '3.8'

services:
  # Backend GraphQL API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event-scheduler-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - JWT_EXPIRES_IN=7d
      - DATABASE_PATH=/app/data/events.db
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - backend_data:/app/data
    networks:
      - event-scheduler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event-scheduler-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_WS_URL=ws://localhost:4000/graphql
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - event-scheduler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local

networks:
  event-scheduler-network:
    driver: bridge 